export const VALORANT_REGIONS: Record<string, string[]> = {
    NA: [
        'Ashburn (Virginia)',
        'Atlanta (Georgia)',
        'Chicago (Illinois)',
        'Dallas (Texas)',
        'Portland (Oregon)',
        'San Jose (California)',
    ],
    EU: [
        'Frankfurt (Germany)',
        'Paris (France)',
        'London (United Kingdom)',
        'Warsaw (Poland)',
        'Stockholm (Sweden)',
        'Madrid (Spain)',
        'Istanbul (Turkey)',
        'Dubai (United Arab Emirates)',
        'Manama (Bahrain)',
        'Cape Town (South Africa)',
    ],
    AP: [
        'Singapore',
        'Hong Kong',
        'Tokyo (Japan)',
        'Mumbai (India)',
        'Sydney (Australia)',
        'Manila (Philippines)',
    ],
    LATAM: [
        'Mexico City (Mexico)',
        'Santiago (Chile)',
        'Miami (Florida, USA)',
        'Bogotá (Colombia)',
    ],
    BR: ['São Paulo'],
    KR: ['Seoul'],
};

export const VALORANT_RANKS: readonly string[] = [
    'Iron 1',
    'Iron 2',
    'Iron 3',
    'Bronze 1',
    'Bronze 2',
    'Bronze 3',
    'Silver 1',
    'Silver 2',
    'Silver 3',
    'Gold 1',
    'Gold 2',
    'Gold 3',
    'Platinum 1',
    'Platinum 2',
    'Platinum 3',
    'Diamond 1',
    'Diamond 2',
    'Diamond 3',
    'Ascendant 1',
    'Ascendant 2',
    'Ascendant 3',
    'Immortal 1',
    'Immortal 2',
    'Immortal 3',
    'Radiant',
] as const;